server:
  port: 9990
  servlet:
    context-path: /ip/

spring:
  datasource:
    url: ${DB_URL}
    password: ${DB_USER}
    username: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

configuration:
  url:
    ipwho: http://ipwho.is
    ipapi: http://ip-api.com/json
